### ISSUE TITLE
[BUG] misconfigured csrf

### ISSUE THREAD

**Issue by stovberpv** [iamolegga/nestjs-session#232]
**What is the current behavior?**

If using this module alongside with `csurf` then got an error `misconfigured csrf`

**Please provide the steps to reproduce.**

1. create new nest project.
1. add `SessionModule.forRoot({ session: { secret: 'secret' } })` to `app.module.ts`.
1. add `app.use(csurf())` to `main.ts`.
1. create a controller to handle request.
1. got the error `misconfigured csrf`.

**What is the expected behavior?**

Do not get this error.

**Please mention other relevant information such as Node.js version and Operating System.**

```
- Nest version: 7.2.0
- Node version: v12.16.3
- Platform: Windows
```

**Comment by iamolegga** [comment]
This bug is in your configuration of `csurf`. Please read docs how to setup it before opening bugs in third-party libs.

This lib is a thin wrapper for `express-session`. See tests and examples how it's used and how it works. It has nothing to do with `csurf`, moreover `csurf` is based on either `express-session` or `cookie-session`, so again if you've got error `misconfigured csrf` maybe it's true

Closing
